services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:8080"
    environment:
      - GIN_MODE=${GIN_MODE}
    restart: always
    networks:
      - app_network

networks:
  app_network:
    name: yuedsen_network
